### ISSUE TITLE
Non-static method BetterSerializer\DataBind\Writer\Type\ExtractorBuilder::build() should not be called statically

### ISSUE THREAD

**Issue by mitec** [better-serializer/better-serializer-bundle#1]
Hi,

when I configured better serializer bundle according the doc (https://github.com/better-serializer/better-serializer-bundle/blob/master/Doc/Configuration.md), serializer initialization ended with the following error:

**PHP Deprecated:  Non-static method BetterSerializer\DataBind\Writer\Type\ExtractorBuilder::build() should not be called statically.**

Please, could you have a check at that.

Thanks a lot

**Comment by Rastusik** [comment]
@mitec The bundle should be updated some time this week, the fix, that you needed is in the dev-master version of better-serializer/better-serializer , so manual update should work for now, if you're in a hurry

**Comment by Rastusik** [comment]
this should be fixed in 0.1.1
